export const BLOCKED_DOMAINS = [
  "slot88",
  "pragmatic",
  "gacor",
  "maxwin",
  "scatter",
  "joker123",
  "joker388",
  "slot777",
  "togel",
  "poker88",
  "domino99",
  "qq88",
  "qqslot",
  "sbobet",
  "188bet",
  "bet365",
  "m88",
  "dewa",
  "dewacasino",
  "dewapoker",
  "dewaslot",
  "slot5000",
  "pulsa5000",
  "olympus",
  "zeus",
  "mahjong",
  "bonanza",
  "starlight",
  "gates-of",
  "sugar-rush",
  "wild-west",
  "sweet-bonanza",
  "lucky-neko",
  "aztec",
  "pgsoft",
  "habanero",
  "microgaming",
  "playtech",
  "spadegaming",
  "cq9",
  "jili",
  "fachai",
  "live22",
  "xe88",
  "pussy888",
  "mega888",
  "918kiss",

  "xxx",
  "porn",
  "adult",
  "casino",
  "gambling",
  "betting",
  "crypto-scam",
  "free-money",
  "win-now",
  "claim-prize",
  "lottery",
];

export const BLOCKED_KEYWORDS = [
  "slot gacor",
  "slot online",
  "judi online",
  "togel online",
  "poker online",
  "casino online",
  "taruhan online",
  "maxwin",
  "jackpot",
  "rtp live",
  "rtp slot",
  "deposit pulsa",
  "scatter hitam",
  "scatter emas",
  "bocoran slot",
  "pola slot",
  "akun pro",
  "situs slot",
  "agen slot",
  "bandar slot",
  "daftar slot",
  "link slot",
  "login slot",
  "prediksi togel",
  "angka jitu",
  "result togel",
  "pengeluaran togel",
  "data hk",
  "data sgp",
  "data sydney",
  "keluaran hk",
  "keluaran sgp",
  "paito warna",
  "bonus new member",
  "bonus deposit",
  "freebet",
  "freechip",
  "depo 10k",
  "depo 25k",
  "minimal deposit",
  "withdraw cepat",
  "wd lancar",
  "anti rungkad",
  "gampang menang",
  "pasti bayar",
  "terpercaya 2024",
  "terpercaya 2025",
  "terpercaya 2026",
  "server thailand",
  "server luar",
  "server kamboja",
  "server vietnam",
  "server filipina",
  "pragmatic play",
  "pg soft",
  "habanero",
];

export const CSP_CONFIG = {
  allowedDomains: [
    "'self'",
    "https://fonts.googleapis.com",
    "https://fonts.gstatic.com",
    "https://www.youtube.com",
    "https://youtube.com",
    "https://www.google.com",
    "https://maps.googleapis.com",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
  ],

  frameSources: [
    "'self'",
    "https://www.youtube.com",
    "https://youtube.com",
    "https://www.google.com",
    "https://maps.google.com",
  ],

  imageSources: ["'self'", "data:", "blob:", "https:"],
};

export const RATE_LIMIT_CONFIG = {
  maxRequests: 100,
  windowMs: 60 * 1000,
  apiMaxRequests: 30,
  maxWebSocketConnections: 5,
};

export const SECURITY_HEADERS = {
  "X-Frame-Options": "SAMEORIGIN",
  "X-Content-Type-Options": "nosniff",
  "X-XSS-Protection": "1; mode=block",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy":
    "camera=(), microphone=(), geolocation=(self), payment=()",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
};

export const TRUSTED_ORIGINS = [
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "https://web-aditiaa.vercel.app",
  "https://utaaa.my.id",
];

export const ALLOWED_FILE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
  "application/pdf",
];

export const MAX_FILE_SIZE = 5 * 1024 * 1024;
